apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
  config:
    retention.ms: {{ .Values.topic.retentionMs }}
    min.insync.replicas: {{ .Values.topic.minInsyncReplicas | quote }}